### ISSUE TITLE
Hi guys

### ISSUE THREAD

**Issue by ltoshev** [SparkleNetworks/LinkedInNET#2]
Hi I have implemented quickly Messaging part of the API, where one can send messages to connections.

I would be very happy to commit it here in a branch to have a review, and merge it to the master :)

**Comment by sandrock** [comment]
Hi,

Nice to see that. Are you familiar with the "fork and pull process"?

In order to share your changes, you Fork this project. This will create a copy for you to change.
Then you Push your changes to your fork.
Finally, you create a pull request from your project to the main one.

https://help.github.com/articles/using-pull-requests/

Tell me if you're alright with that.

**Comment by sandrock** [comment]
How is it going?

**Comment by sandrock** [comment]
Wanna post me your changes elsewhere if the fork process is too obscure for you? Post the changes in the XML file here is it's small...

**Comment by ltoshev** [comment]
Hi

sorry champ, I was very very busy and by looking at my code I did not implement it into the xml that emtis the code, but directly into the code, because I was not sure at the time how to do the xml.

Here you get the zipped code of the library + a file how do I use it in my code. You should be able to figure it our. I am so damn busy with paid projects I do not have time to deal with this now.

download the code from here https://www.dropbox.com/s/9vqap7aeyokrvlg/sparkle-code.rar?dl=0

**Comment by sandrock** [comment]
We won't be able to use this code. Thank you for your contribution.
